import type { CreativeModePanelProps } from '../../apps/frontend/src/components/Editor/comparison-lab/modes/CreativeModePanel'

const noop = (() => {}) as (...args: any[]) => void

export const createCreativeModePanelProps = (
  overrides: Partial<CreativeModePanelProps> = {}
): CreativeModePanelProps =>
  ({
    creativeScript: '',
    creativeStyle: 'cinematic',
    commitScore: 0.8,
    isCreativeBusy: false,
    creativeRun: null,
    creativeRunFeedback: '',
    sceneFeedbackMap: {},
    creativeVersions: [],
    geminiQuickCheck: {
      status: 'ready',
      title: 'Gemini Veo 3.1 已就绪',
      description: '可直接创建视频生成任务。'
    },
    videoGenerationMode: 'text_to_video',
    videoGenerationModelId: 'veo-3.1',
    videoGenerationPrompt: '',
    videoGenerationNegativePrompt: '',
    videoGenerationInputSourceType: 'url',
    videoGenerationImageInput: '',
    videoGenerationReferenceImagesInput: '',
    videoGenerationVideoInput: '',
    videoGenerationFirstFrameInput: '',
    videoGenerationLastFrameInput: '',
    videoGenerationListLimit: '20',
    videoGenerationStatusFilter: 'all',
    videoGenerationJobs: [],
    videoGenerationCursor: '',
    videoGenerationHasMore: false,
    videoGenerationSelectedJobId: '',
    videoGenerationPollingEnabled: true,
    videoGenerationLastAutoSyncAt: '',
    isVideoGenerationAutoSyncTicking: false,
    isVideoGenerationBusy: false,
    workflows: [],
    selectedWorkflowId: '',
    workflowName: '',
    workflowDescription: '',
    workflowRunPayload: '{}',
    workflowRunResult: null,
    workflowRuns: [],
    workflowRunsLimit: '20',
    workflowRunsHasMore: false,
    batchJobType: 'render.batch',
    batchJobPayload: '{"items":[]}',
    batchJobId: '',
    batchJobStatus: null,
    assetReuseSourceId: '',
    assetReuseTargetId: '',
    assetReuseNote: '',
    assetReuseResult: null,
    assetReuseHistoryAssetId: '',
    assetReuseHistorySourceProjectId: '',
    assetReuseHistoryTargetProjectId: '',
    assetReuseHistoryLimit: '20',
    assetReuseHistoryOffset: '0',
    assetReuseHistoryRecords: [],
    isV4Busy: false,
    onCreativeScriptChange: noop,
    onCreativeStyleChange: noop,
    onCommitScoreChange: noop,
    onCreateCreativeRun: noop,
    onApplyCreativeFeedback: noop,
    onCommitCreativeRun: noop,
    onRefreshCreativeVersions: noop,
    onRunGeminiQuickCheck: noop,
    onOpenChannelPanel: noop,
    onVideoGenerationModeChange: noop,
    onVideoGenerationModelIdChange: noop,
    onVideoGenerationPromptChange: noop,
    onVideoGenerationNegativePromptChange: noop,
    onVideoGenerationInputSourceTypeChange: noop,
    onVideoGenerationImageInputChange: noop,
    onVideoGenerationReferenceImagesInputChange: noop,
    onVideoGenerationVideoInputChange: noop,
    onVideoGenerationFirstFrameInputChange: noop,
    onVideoGenerationLastFrameInputChange: noop,
    onVideoGenerationListLimitChange: noop,
    onVideoGenerationStatusFilterChange: noop,
    onVideoGenerationSelectedJobIdChange: noop,
    onVideoGenerationPollingEnabledChange: noop,
    onCreateVideoGenerationTask: noop,
    onRefreshVideoGenerationJobs: noop,
    onLoadMoreVideoGenerationJobs: noop,
    onQueryVideoGenerationJobDetail: noop,
    onSyncVideoGenerationJob: noop,
    onRetryVideoGenerationJob: noop,
    onCancelVideoGenerationJob: noop,
    onRefreshVideoGenerationJobDetail: noop,
    onCreativeRunFeedbackChange: noop,
    onSceneFeedbackChange: noop,
    onSwitchCreativeRunVersion: noop,
    onRefreshWorkflows: noop,
    onSelectedWorkflowIdChange: noop,
    onWorkflowNameChange: noop,
    onWorkflowDescriptionChange: noop,
    onWorkflowRunPayloadChange: noop,
    onCreateWorkflow: noop,
    onRunWorkflow: noop,
    onWorkflowRunsLimitChange: noop,
    onQueryWorkflowRuns: noop,
    onLoadMoreWorkflowRuns: noop,
    onBatchJobTypeChange: noop,
    onBatchJobPayloadChange: noop,
    onBatchJobIdChange: noop,
    onCreateBatchJob: noop,
    onQueryBatchJob: noop,
    onAssetReuseSourceIdChange: noop,
    onAssetReuseTargetIdChange: noop,
    onAssetReuseNoteChange: noop,
    onCallAssetReuse: noop,
    onAssetReuseHistoryAssetIdChange: noop,
    onAssetReuseHistorySourceProjectIdChange: noop,
    onAssetReuseHistoryTargetProjectIdChange: noop,
    onAssetReuseHistoryLimitChange: noop,
    onAssetReuseHistoryOffsetChange: noop,
    onQueryAssetReuseHistory: noop,
    ...overrides
  }) as CreativeModePanelProps
